# edit the following three version numbers
SET(VERSION_MAJOR 0)
SET(VERSION_MINOR 1)
SET(VERSION_RELEASE 0)

# this is from makefile, do not edit it
SET(VERSION_STRING "$(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_RELEASE)")
SET(SOVERSION_STRING "$(VERSION_MAJOR).$(VERSION_MINOR)")
